server:
  port: 7003

#Eureka配置
eureka:
  instance:
    hostname: eurka7003.com  #eureka服务端的实例名称
  client:
    register-with-eureka: false #是否像eureka注册中心注册自己
    fetch-registry: false  #fetch-registry:false表示自己为注册中心
    service-url: # 监控页面
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/